name: My CI Pipeline  # Название workflow

on:
  push:  # Запускается при пуше в репозиторий
    branches:
      - main

jobs:
  build:  # Название задачи (job)
    runs-on: ubuntu-latest  # На какой ОС будет выполняться job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Официальный action для клонирования репозитория

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest  # Запуск тестов
